Local sahifa tayyor
MMBobur/acme-website pull request #3
Opened 2022-02-27 15:01 UTC by sardorbek9090

Asosiy rasm orniga boshqa rasm qoydim. Chunki u rasmni topapa olmadim.

2022-02-27 22:40 UTC, Prince4347 approved these changes
Sardor akani kodi

2022-02-27 22:42 UTC, RegnumUz approved these changes

2022-02-27 22:43 UTC, RegnumUz approved these changes
tayyor

2022-02-27 22:45 UTC, RegnumUz requested changes
Gdfzfb

2022-02-27 22:45 UTC, Prince4347 approved these changes
tekshirildi

2022-02-27 22:46 UTC, Prince4347 commented
tayyor

2022-02-28 18:38 UTC, RegnumUz approved these changes
tayyor

2022-02-28 18:39 UTC, RegnumUz approved these changes

2022-02-28 18:53 UTC, merged